### ISSUE TITLE
Create a COMMON config file.

### ISSUE THREAD

**Issue by Zokr4m** [Tourmi/mc-server-side-vein-miner#53] opened 2024-09-22 00:25 UTC
## Feature
**Common config file**

* Simply create a config file in the **config** folder of .minecraft mods

## Impact
* You will no longer have to copy paste the config file into every new world you generate.
* Will be a problem with / commands, I would suggest removing them if this is implemented.

**Comment by Tourmi** [comment] 2024-09-28 18:16
Duplicate of #19

**Closed by Tourmi** 2024-09-28 18:16 UTC
Labels: duplicate, enhancement
